name: Testing Render

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - run: pip install click
      - name: Run with terminal size
        env:
          COLUMNS: 80
          LINES: 25
        run: python3 -c "import click; click.secho('Hello World without whitespace', fg='green'); click.secho('  Hello World with styled whitespace', fg='green'); click.echo('  ' + click.style('Hello World with non-styled whitespace', fg='green'))"


